NewGame: New game
Track: Track
NumPlayers: Number of players
CreateGame: Create game
DotRace: Dot Race
Help: Help
JoinGame: Join game
Name: Name
Join: Join
GameOver: Game Over!
Boom: Boom!
Crash: There was an accident on the track! The race is over!
Congratulations: Congratulations!
YouWon: You won the race!
YouLose: You lose!
HasWon: has won the race.
GeneralRules: General rules
Movement: Movement
Inviting: Inviting more players
ToInvite: To invite your friends to the game, simply send them the URL of the page.
MoveGeneral: When it is your turn to move, you will be presented with gray dots indicating your options where to move. It is essential for the game to understand how these options are determined.
MoveFromStill: If you are starting to move, you can move to any adjacent spot that is on the track and not already occupied by someone else.
MoveNext: If you moved in the previous turn, your first option will be determined by duplicating your previous move. All its adjacent spots will also be possible movement destination.
MoveObstacle: You can not move to a spot that is hidden behind a corner. In other words the straight line between you current position and desired destination can not cross the track outline.
Close: Close
Goal: The goal of the game is to be the first to cross the finish line.
Mechanics: When new game is created, all players must join the game for the race to begin. Then, players take turns to move and try to reach the finish line as fast as possible while avoiding crashing into the wall.
Direction: The direction in which to go is not set and players are free to agree on which direction they want.
Blurb: In-browser multiplayer turn-based racing game.
Start: Start new game
JoinExisting: Join existing game
JoinMethod: To join an existing game, simply follow the link send to you by the game creator.
AfterJoin: You will be taken to the game screen, where you can enter your name and join the game.
AllReady: Once all players joined the game, racing can start.
HowTo: How to play
Intro: You control a racing car. The goal is to be the first to cross the finish line.
BriefRules: The rules of moving are actually pretty simple. The best way to understand them is to start a race with one player and play around with it. Help contains precise description of how it works.
